export const keywordWeights: Record<string, number> = {
  "software engineer": 25,
  "software developer": 25,
  backend: 20,
  "back-end": 20,
  frontend: 20,
  "front-end": 20,
  "full stack": 20,
  fullstack: 20,

  react: 15,
  typescript: 15,
  javascript: 12,
  node: 12,
  "node.js": 12,
  java: 12,
  spring: 12,
  api: 10,
  rest: 8,

  remote: 15,
  remoto: 15,
  brazil: 15,
  brasil: 15,
  latam: 15,
  "latin america": 15,

  junior: 10,
  jr: 10,
  pleno: 8,
  "mid-level": 8,
  desenvolvedor: 20,
  desenvolvedora: 20,
  "desenvolvedor backend": 25,
  "desenvolvedora backend": 25,
  "desenvolvedor frontend": 25,
  "desenvolvedora frontend": 25,
  "desenvolvedor full stack": 25,
  "desenvolvedora full stack": 25,
  "analista de sistemas": 15,
  "engenheiro de software": 25,
  "engenheira de software": 25,
  clt: 10,
  pj: 8,
  senior: -20,
  "sr.": -20,
  sênior: -20,
  php: -10,
};

export const forbiddenKeywords = [
  "freelancer",
  "freela",
  "freelance",
  "bico",
  "estágio",
  "estagio",
  "internship",
  "sales",
  "marketing",
  "designer",
  "product manager",
  "customer support",
  "atendimento",
  "call center",
  "telemarketing",
  "engineering manager",
  "director",
  "principal",
  "staff engineer",
];
